### ISSUE TITLE
java.lang.IllegalStateException: AppCompat has already installed itself into the Window

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#108]
This error occurs mostly on kitkat ar Now Playing screen. @marverenic

**Comment by Dirkstaal** [comment]
@iampawan i know this is an issue but i need help what android studio version are you using ect because my layouts shows only coordinator layout text with an gray background.

**Comment by marverenic** [comment]
Is this an actual crash or just an error that gets logged to the console? I don't think I've seen this show up in the Crashlytics dashboard.

It would also help if you posted the full stack trace and let me know which version of Jockey you're running (e.g. 1.2 - latest stable, 2.0 beta 2 - latest beta, or a compiled version of `master`). If you can consistently trigger this error, then it would be great if you could provide reproduction steps.

**Comment by iampawan** [comment]
1. It is an actual crash.
2. It mostly happens on prelollipop devices.
3. It happens rarely so not able to reproduce. 
4. It happens with the latest version .
5. I will let you know if i would be able to reproduce it .

**Comment by iampawan** [comment]
@marverenic  Someone send me this logs . This happens on NowPlaying . This is a major issue and its a crash.Please help
Caused by java.lang.IllegalStateException: AppCompat has already installed itself into the Window
       at android.support.v7.app.AppCompatDelegateImplBase.(AppCompatDelegateImplBase.java:74)
       at android.support.v7.app.AppCompatDelegateImplV7.(AppCompatDelegateImplV7.java:146)
       at android.support.v7.app.AppCompatDelegateImplV11.(AppCompatDelegateImplV11.java:28)
       at android.support.v7.app.AppCompatDelegateImplV14.(AppCompatDelegateImplV14.java:41)
       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
       at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
       at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onCreate(RxAppCompatActivity.java:43)

**Comment by marverenic** [comment]
Thanks for the info, but I don't know if it's enough to debug this. Can you post the full stacktrace?

I'm also a bit confused why this still hasn't been reported to Crashlytics. Are you using the version from the Google Play Store, or have you built Jockey yourself? Also, what devices are experiencing this behavior? Are any of them rooted or running custom ROMs?

(By the way, you don't have to mention me with `@marverenic` on threads in Jockey's repo – I already get emails about everything that's posted)

**Comment by marverenic** [comment]
I'm going to go ahead and close this issue due to inactivity. Jockey has upgraded its version of the support libraries several times since this was opened, and I have not been able to reproduce this issue. If it is still a problem, please feel free to open a new issue.

**Comment by landoulsi** [comment]
I am still able to reproduce the issue in tests :
Test code : 
`    @Test
    public void testWebViewCloseButton_hide() {
        setUpCityConfigWithWebViewCloseButtonHidden(true);
        final GenericWebViewActivity genericWebViewActivity =
                Robolectric.setupActivity(GenericWebViewActivity.class);
        final View closeButton = genericWebViewActivity.findViewById(R.id.close_btn);
        Assertions.assertThat(closeButton).isGone();
    }
`

StackTrace :
`java.lang.IllegalStateException: AppCompat has already installed itself into the Window
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:122)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.getMenuInflater(AppCompatActivity.java:135)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2821)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
	at android.support.v7.app.AppCompatDelegateImplV9.preparePanel(AppCompatDelegateImplV9.java:1368)
	at android.support.v7.app.AppCompatDelegateImplV9.doInvalidatePanelMenu(AppCompatDelegateImplV9.java:1648)
	at android.support.v7.app.AppCompatDelegateImplV9$1.run(AppCompatDelegateImplV9.java:140)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:164)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:138)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:360)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:259)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:240)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:223)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:213)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:80)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:115)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:317)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:368)
	at org.robolectric.shadows.CoreShadowsAdapter$1.runPaused(CoreShadowsAdapter.java:27)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:70)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:80)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:172)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:102)`

**Comment by marverenic** [comment]
I'm not sure where that unit test is coming from since Jockey doesn't use WebView anywhere. It's also very possible that this test is failing because of a problem with Robolectric or your unit tests.

Please let me know if you're able to reproduce this exception in Jockey on a physical device.
