### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#13]
Found a bug, please look into it
```
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.b.c.d(Unknown Source)
	at android.support.v4.app.Fragment.h(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.v.e(Unknown Source)
	at android.support.v4.app.v.b(Unknown Source)
	at android.support.v4.app.aa.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.c(Unknown Source)
	at android.support.v4.view.ce.run(Unknown Source)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Micromax Micromax A310
Android version 4.4.2
Java max heap size: 128MB
Device memory: 1969 MB
Locale: en_US
Network Status: type: mobile, state: CONNECTED
java.lang.NullPointerException
	at com.marverenic.music.activity.SearchActivity.onCreateOptionsMenu(Unknown Source)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2571)
	at android.support.v4.app.o.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.e.a(Unknown Source)
	at android.support.v7.app.g.a(Unknown Source)
	at android.support.v7.widget.au.a(Unknown Source)
	at android.support.v7.internal.a.a.f(Unknown Source)
	at android.support.v7.internal.a.b.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Micromax Micromax A310
Android version 4.4.2
Java max heap size: 128MB
Device memory: 1969 MB
Locale: en_US
Network Status: type: mobile, state: CONNECTED
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.b.c.d(Unknown Source)
	at android.support.v4.app.Fragment.h(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.v.e(Unknown Source)
	at android.support.v4.app.v.b(Unknown Source)
	at android.support.v4.app.aa.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItem(Unknown Source)
	at com.marverenic.music.view.e.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Micromax Micromax A310
Android version 4.4.2
Java max heap size: 128MB
Device memory: 1969 MB
Locale: en_US
Network Status: type: mobile, state: CONNECTED
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.b.c.d(Unknown Source)
	at android.support.v4.app.Fragment.h(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.Fragment.c(Unknown Source)
	at android.support.v4.app.aa.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItem(Unknown Source)
	at com.marverenic.music.view.e.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Micromax Micromax A310
Android version 4.4.2
Java max heap size: 128MB
Device memory: 1969 MB
Locale: en_US
Network Status: type: mobile, state: CONNECTED
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.a.q.<init>(Unknown Source)
	at com.marverenic.music.b.c.d(Unknown Source)
	at android.support.v4.app.Fragment.h(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.v.e(Unknown Source)
	at android.support.v4.app.v.b(Unknown Source)
	at android.support.v4.app.aa.b(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItem(Unknown Source)
	at com.marverenic.music.view.e.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Micromax Micromax A310
Android version 4.4.2
Java max heap size: 128MB
Device memory: 1969 MB
Locale: en_US
Network Status: type: mobile, state: CONNECTED
```

**Comment by captainfenix** [comment]
Also, with XposedFramework enabled, it seems to crash, I don't know why.

**Comment by marverenic** [comment]
Unfortunately having proguard obfuscate all of the class names isn't helping that much, so I've disabled that in the new build. If you wouldn't mind reproducing the bug again and submitting the bug report again that'd be great.

Also, sorry for the lack of communication over the past two weeks. The end of this semester and finals were a bit stressful, so I've been taking a bit of a break on Jockey. I intend to work on it more over the summer, but I just haven't worked on it too much recently.

**Comment by captainfenix** [comment]
Got my semester starting up this day next week, I'll generate the log asap. Will report in some moments. :)

**Comment by captainfenix** [comment]
Generated Log from the latest version. FYI I have XposedFramework installed on my tablet/phones.

```
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at com.marverenic.music.adapters.GenreListAdapter.<init>(Unknown Source)
	at com.marverenic.music.adapters.GenreListAdapter.<init>(Unknown Source)
	at com.marverenic.music.fragments.GenreFragment.onCreate(Unknown Source)
	at android.support.v4.app.Fragment.performCreate(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.v.a(Unknown Source)
	at android.support.v4.app.e.run(Unknown Source)
	at android.support.v4.app.v.e(Unknown Source)
	at android.support.v4.app.v.b(Unknown Source)
	at android.support.v4.app.aa.finishUpdate(Unknown Source)
	at android.support.v4.view.ViewPager.a(Unknown Source)
	at android.support.v4.view.ViewPager.c(Unknown Source)
	at android.support.v4.view.da.run(Unknown Source)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Jockey 0.2-α.r0m20e (build 22004)
Lenovo LenovoA3300-GV
Android version 4.4.2
Java max heap size: 128MB
Device memory: 961 MB
Locale: en_US
Network Status: type: WIFI, state: CONNECTED
```

Hope this helps

**Comment by captainfenix** [comment]
Another issue where in it crashes when I click on any artist. Tried on both phone/tab.

```
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
	at android.widget.ListView.setupChild(ListView.java:1848)
	at android.widget.ListView.makeAndAddView(ListView.java:1815)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1631)
	at android.widget.AbsListView.onLayout(AbsListView.java:2149)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2323)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2029)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Jockey 0.2-α.r0m20e (build 22004)
Lenovo LenovoA3300-GV
Android version 4.4.2
Java max heap size: 128MB
Device memory: 961 MB
Locale: en_US
Network Status: type: WIFI, state: CONNECTED
```

Hope it helps too

**Comment by captainfenix** [comment]
Crashes when I click on search.

```
java.lang.NullPointerException
	at com.marverenic.music.activity.SearchActivity.onCreateOptionsMenu(Unknown Source)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2571)
	at android.support.v4.app.o.onCreatePanelMenu(Unknown Source)
	at android.support.v7.internal.view.k.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.u.onCreatePanelMenu(Unknown Source)
	at android.support.v7.internal.view.k.onCreatePanelMenu(Unknown Source)
	at android.support.v7.internal.a.b.f(Unknown Source)
	at android.support.v7.internal.a.c.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

[DEVICE INFO]
Jockey 0.2-α.r0m20e (build 22004)
Lenovo LenovoA3300-GV
Android version 4.4.2
Java max heap size: 128MB
Device memory: 961 MB
Locale: en_US
Network Status: type: WIFI, state: CONNECTED
```

**Comment by captainfenix** [comment]
Doesn't play next song when removed from recent apps, shows next song impn notification but won't play it. Plus when you click on it, it goes back to some random part in the previous song.

**Comment by marverenic** [comment]
Thanks. I don't think XPosed is responsible for anything, but I'll look into it.

I think I've found and fixed the problem you had from the first log. It looks like one of your genre names had a format that Jockey wasn't expecting, so it should now check and ignore certain cases.

I've also reproduced the second problem in a 4.4 emulator. I think I changed a layout that Lollipop uses but forgot to change it for older versions of Android.

I'm not exactly sure why search is crashing. It might have something to do with AppCompat-v7, but I haven't reproduced it yet.

**Comment by captainfenix** [comment]
Well search doesn't work on 4 phones I've checked on, same logs throughout.

**Comment by marverenic** [comment]
I found the problem. It was caused by proguard obfuscating the the SearchView class which is why it didn't show up in debug builds.

I've just pushed a new build that addresses these issues. Please let me know if it resolves them.

**Comment by captainfenix** [comment]
Alright will take a look asap and report.

**Comment by captainfenix** [comment]
Srill have the crash on albums page.

**Comment by captainfenix** [comment]
Artist, Search is working now, album crashes
